version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c 'python manage.py migrate && python manage.py collectstatic && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/django_projects
    ports:
      - "8000:8000"
    depends_on:
      - db
